//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hizmet_MusMemnuniyet
{
    using System;
    using System.Collections.Generic;
    
    public partial class HizmetCRM_Musteriler
    {
        public int MusteriID { get; set; }
        public string AdSoyad { get; set; }
        public string Meslek { get; set; }
        public string CepTlf { get; set; }
        public string SabitTlf { get; set; }
        public string Adres { get; set; }
        public string Eposta { get; set; }
        public string DogumTarihi { get; set; }
        public Nullable<bool> Dogum { get; set; }
        public Nullable<int> DogumAy { get; set; }
        public Nullable<int> DogumGun { get; set; }
        public string EvlilikTarihi { get; set; }
        public Nullable<bool> Evlilik { get; set; }
        public Nullable<int> EvlilikAy { get; set; }
        public Nullable<int> EvlilikGun { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
