//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hizmet_MusMemnuniyet
{
    using System;
    using System.Collections.Generic;
    
    public partial class HizmetCRM_YeniAnket
    {
        public int AnketID { get; set; }
        public Nullable<System.DateTime> AnketTarih { get; set; }
        public Nullable<System.DateTime> AramaTarih { get; set; }
        public string Numara { get; set; }
        public string AnketYorumu { get; set; }
        public string AnketRaporu { get; set; }
        public string GorusmeSonucu { get; set; }
        public string UlasimSecenegi { get; set; }
        public Nullable<int> SubeID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> HizmetID { get; set; }
        public bool IsActive { get; set; }
    }
}
