//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hizmet_MusMemnuniyet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class HizmetCRMEntities : DbContext
    {
        public HizmetCRMEntities()
                    //: base("name=HizmetCRMEntities")
                    : base(@"metadata=res://*/HizmetCRM.csdl|res://*/HizmetCRM.ssdl|res://*/HizmetCRM.msl;provider=System.Data.SQLite.EF6;provider connection string=""data source=" + System.Environment.CurrentDirectory + @"\Data\HizmetCRM.db3""")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<HizmetCRM_AnaKategori> HizmetCRM_AnaKategori { get; set; }
        public virtual DbSet<HizmetCRM_Hizmetler> HizmetCRM_Hizmetler { get; set; }
        public virtual DbSet<HizmetCRM_Kategori> HizmetCRM_Kategori { get; set; }
        public virtual DbSet<HizmetCRM_Kullanicilar> HizmetCRM_Kullanicilar { get; set; }
        public virtual DbSet<HizmetCRM_Loglar> HizmetCRM_Loglar { get; set; }
        public virtual DbSet<HizmetCRM_Musteriler> HizmetCRM_Musteriler { get; set; }
        public virtual DbSet<HizmetCRM_Personel> HizmetCRM_Personel { get; set; }
        public virtual DbSet<HizmetCRM_ServisOlumlu> HizmetCRM_ServisOlumlu { get; set; }
        public virtual DbSet<HizmetCRM_ServisOlumsuz> HizmetCRM_ServisOlumsuz { get; set; }
        public virtual DbSet<HizmetCRM_Subeler> HizmetCRM_Subeler { get; set; }
        public virtual DbSet<HizmetCRM_YeniAnket> HizmetCRM_YeniAnket { get; set; }
        public virtual DbSet<Hizmetcrm_FormView> Hizmetcrm_FormView { get; set; }
    }
}
