//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hizmet_MusMemnuniyet
{
    using System;
    using System.Collections.Generic;
    
    public partial class HizmetCRM_Loglar
    {
        public int LogID { get; set; }
        public string Aciklama { get; set; }
        public string Modul { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
