//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hizmet_MusMemnuniyet
{
    using System;
    using System.Collections.Generic;
    
    public partial class HizmetCRM_ServisOlumlu
    {
        public int KategoriOlumluID { get; set; }
        public Nullable<int> AnketID { get; set; }
        public Nullable<int> KategoriID { get; set; }
    }
}
